### ISSUE TITLE
New home page in frontend: Click on component not possible everywhere

### ISSUE THREAD

**Issue by davidkopp** [green-coding-solutions/green-metrics-tool#1115]
On the new home page in the GMT frontend (https://metrics.green-coding.io/index.html) only the logo of a component is clickable at the moment. A click on the name (e.g. ScenarioRunner) or in general on the bottom part does not work.

This seems to be a bug, because the animation indicates that everything should be clickable.

**Comment by ribalba** [comment]
I can not reproduce. What OS/ Browser etc are you using?
Are you getting an error in the JS console?

**Comment by davidkopp** [comment]
I have this issue with all my browsers (firefox, firefox developer, chromium, brave), both on desktop (Win11) and mobile (Android).
There is no error in the dev console.

**Comment by davidkopp** [comment]
Only during loading of the page there is one error in the dev console:

```plain
Uncaught (in promise) TypeError: document.querySelector(...) is null
    <anonymous> https://metrics.green-coding.io/js/helpers/runs.js:269
    <anonymous> https://metrics.green-coding.io/js/helpers/runs.js:301
```

I have not checked if it is related to this issue.

**Comment by ArneTR** [comment]
I can reproduce it. Indeed unnecessarily confusing. Will push a fix soon

**Comment by ArneTR** [comment]
ty for the issue!

**Comment by ArneTR** [comment]
Should be fixed now:

- [5f68d7f0b81d039948bf9eff50f49988e43b0a4c](https://github.com/green-coding-solutions/green-metrics-tool/commit/51bd0542d3342d292bff861ba76fba2146a805e8)
- [51bd0542d3342d292bff861ba76fba2146a805e8](https://github.com/green-coding-solutions/green-metrics-tool/commit/5f68d7f0b81d039948bf9eff50f49988e43b0a4c)

Also online

**Comment by davidkopp** [comment]
The name is now clickable.
There is still an issue. If my mouse cursor is at the bottom of the component it changes to the cursor that indicates it is clickable. However, it isn't.

**Comment by ArneTR** [comment]
ok ... that was a tricky one ... had to fight with the flexbox model.

Now shoud be done: https://github.com/green-coding-solutions/green-metrics-tool/commit/5270e915532bd6af393a1d1fe2d860d453d9f76f

Also online
